version: 2.1

orbs:
  nx: nrwl/nx@1.3.0

jobs:
  analyze:
    docker:
      - image: 'cimg/node:16.14.2-browsers'
    steps:
      - checkout
      - run:
          command: npm ci
          name: Install dependencies
      - nx/set-shas
      - run:
          command: npx nx affected --target=lint --base=$NX_BASE --parallel
          name: Run Linting
  build:
    docker:
      - image: 'cimg/node:16.14.2-browsers'
    steps:
      - checkout
      - run:
          command: npm ci
          name: Install dependencies
      - nx/set-shas
      - run:
          command: npx nx affected --target=test --base=$NX_BASE --parallel
          name: Run Unit Tests
  test:
    docker:
      - image: 'cimg/node:16.14.2-browsers'
    steps:
      - checkout
      - run:
          command: npm ci
          name: Install dependencies
      - nx/set-shas
      - run:
          command: npx nx affected --target=test --base=$NX_BASE --parallel
          name: Run Unit Tests
  e2e:
    docker:
      - image: 'cimg/node:16.14.2-browsers'
    steps:
      - checkout
      - run:
          command: npm ci
          name: Install dependencies
      - nx/set-shas
      - run:
          command: npx nx affected --target=e2e --base=$NX_BASE
          name: Run Integration Tests

workflows:
  version: 2
  build_and_test:
    jobs:
      - analyze
      - build
      - test
      - e2e
