version: 2.1

orbs:
  nx: nrwl/nx@1.3.0

jobs:
  build:
    docker:
      - image: 'cimg/node:16.14.2-browsers'
    steps:
      - checkout
      - run:
          command: npm ci
          name: Install dependencies
      - nx/set-shas
      - run:
          command: yarn nx affected --target=build --base=$NX_BASE
          name: Run Builds
      - run:
          command: yarn nx affected --target=test --base=$NX_BASE
          name: Run Unit Tests
          
workflows: null
